---
title: "Kevin Clark"
format:
  html:
    toc: true
    grid:
      sidebar-width: 50px
      body-width: 800px
      margin-width: 200px
      gutter-width: 1.5rem
  pdf:
    pdf-engine: weasyprint
css: cv.css
execute:
  echo: false
format-links: [pdf]
---

```{python}
#| tags: [parameters]

email = 'tevin98@gmail.com'
github = 'kevinwc3'
linkedin =  'kevinclark'
telephone = '208 760-2902'
```

```{python}
import polars as pl
from IPython.display import Markdown
```

____

:::: {.columns}

::: {.column width="22%"}
I want to email here is my `{python} Markdown(f'[{email}](mailto:{email})')`
:::

::: {.column width="1%"}
:::

::: {.column width="22%"}
`{python} Markdown(f'[github.com/{github}](https://github.com/{github})')`
:::

::: {.column width="1%"}
:::

::: {.column width="22%"}
`{python} Markdown(f'[linkedin.com/in/{linkedin}](https://www.linkedin.com/in/{linkedin}/)')`
:::

::: {.column width="1%"}
:::


::: {.column width="22%"}
`{python} Markdown(f'[{telephone}](tel:{telephone})')`
:::


::::

____



::: {.print-only .contact-block}
cynthia.huang@monash.edu
:::


## EDUCATION

**Bachelor's -- Data Science** <br> *Brigham Young University-Idaho* **Graduation:** [*Apr 2025*]{.cvdate}

## Certificates and Skills

- Statistics Certificate (Brigham Young University - Idaho)
- Machine Learning Certificate (Brigham Young University - Idaho)
- Coding (Python, R, SQL)
- Data Visualization (Power BI, Python, R, Excel, Tableau)
- Classwork (Big Data Programming, Data Wrangling and Visualization, Applied Calculus, Linear Algebra)

## WORK EXPERIENCE{style="page-break-before: always"}

### Data Science Intern / BI Analyst

***Eastern Idaho Public Health*** [Sep 2024 -- Present]{.cvdate}

- Trained Epidemiologists, Fiscal Officers, and Executive Officers on how to create reports in Power BI.
- Rebuilt and created Power BI dashboards on over 100,000 patients and appointments.
- Rerouted various reports to update more autonomously.
- Created visualizations and wrangled data in R and Python.

### HR Data Analyst Intern

***Church of Jesus Christ of Latter-day Saints*** [Apr 2023 -- Apr 2024]{.cvdate}

- Designed a dashboard in Power BI to visualize HR related data of over 1300 employees.
- Wrote code in Python to wrangle and transform over 800,000 rows of data for my dashboard.
- Automated weekly auditing processes with Python.
- Presented orientation for new hires bi-weekly.

### Student Researcher and Measurement Specialist

***Brigham Young University - Idaho*** [November 2021 -- Present]{.cvdate}

- Maintained dashboards in Power BI with data for over 20,000 students.
- Tested Qualtrics surveys in R and Python to make sure data was being recorded properly.
- Analyzed data to determine what contributed the most to student success.
- Wrangled and combined over 20 datasets in R to make our data easier to analyze.
- Built and distributed multiple surveys in Qualtrics for over 20,000 students every semester.

::: {.no-print}
## Projects

### Data Science Society

***Student*** [Jan 2023 -- Jul 2024]{.cvdate}

- Cleaned datasets containing thousands of variables to determine how accurate our data was.
- Communicated with multiple team members and faculty to make sure we were all contributing and on the same page.
- Compared our clean data using the ANOVA test to find significant variance.

### Data Science Consulting

***Student*** [Sep 2024 -- Dec 2024]{.cvdate}

- Constructed thousands of rows of artificial data in Python.
- Calculated TF-IDF scores for clustering documents.
- Visualized 10,000 clustered documents over a time series.

:::

::: {.print-only}
## References
Available upon request
:::